---
apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: helloworld
  namespace: default
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: helloworld
  service:
    port: 8080
  analysis:
    interval: 10s
    threshold: 5
    stepWeight: 10
    maxWeight: 100
    metrics:
      - name: request-success-rate
        thresholdRange:
          min: 99
        interval: 1m
      - name: request-duration
        thresholdRange:
          max: 500
        interval: 1m
      - name: "404s percentage"
        threshold: 3
        query: |
          100 - sum(
              rate(
                  response_total{
                      namespace="default",
                      deployment="helloworld",
                      status_code!="404",
                      direction="inbound"
                  }[1m]
              )
          )
          /
          sum(
              rate(
                  response_total{
                      namespace="default",
                      deployment="helloworld",
                      direction="inbound"
                  }[1m]
              )
          )
          * 100
    webhooks:
      - name: acceptance-test
        type: pre-rollout
        url: http://flagger-loadtester.flagger-system/
        timeout: 30s
        metadata:
          type: bash
          cmd: "curl -s http://helloworld.default:8080/ | grep -i hello"
      - name: load-test
        type: rollout
        url: http://flagger-loadtester.flagger-system/
        metadata:
          cmd: "hey -z 1m -q 10 -c 2 http://helloworld.default:8080/"

